apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: 99-problems
  name: problem-1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        resources:
          requests:
            cpu: 1250m
