apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: 99-problems
  name: problem-3
spec:
  selector:
    matchLabels:
      app: problem-3
  template:
    metadata:
      labels:
        app: problem-3
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 1
          periodSeconds: 1
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: 99-problems
  name: problem-3
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 8080
  selector:
    app: problem-3
